// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zepjbskpnhizugkdmxdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplcGpic2twbmhpenVna2RteGRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNzU4NDIsImV4cCI6MjA3Nzk1MTg0Mn0.9dG-A-JDSir5KXDWT9xMP3RHwLOrgUO0pW-jQWo5YU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});